fixing

diff --git a/.github/workflows/full_stage_deployment.yml b/.github/workflows/full_stage_deployment.yml
--- a/.github/workflows/full_stage_deployment.yml
+++ b/.github/workflows/full_stage_deployment.yml
@@ -19,6 +19,15 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Check if AWS_ACCESS_KEY_ID is set
+        run: |
+          if [ -z "${{ secrets.AWS_ACCESS_KEY }}" ]; then
+            echo "❌ AWS_ACCESS_KEY_ID is missing"
+            exit 1
+          else
+            echo "✅ AWS_ACCESS_KEY_ID is set"
+          fi
+
       - name: Configure AWS
         uses: aws-actions/configure-aws-credentials@v2
         with:
@@ -28,7 +37,7 @@ jobs:
     
       - name: Verify AWS identity
         run: aws sts get-caller-identity
-        
+
       - name: Set environment
         id: env
         run: |
